### ISSUE TITLE
How to use with SteamGuard ?

### ISSUE THREAD

**Issue by Coriou** [DoctorMcKay/node-steam-client#11]
As always with Valve, documentation is scarce and often inaccurate so I can't find how to pass the SteamGuard authentication code to the `logOn` method. 

I'm guessing it's another field to add to the payload, but I can't find the key... I tried "guard", "auth", ... in a pure "I'm feeling lucky" spirit. Weren't lucky unfortunately. 

Any idea or source of documentation someone could link me please ?

**Comment by Coriou** [comment]
Ok, after a bit more digging and just after posting this issue (as always), I found the solution (in [steammessages_clientserver_login.proto](https://github.com/DoctorMcKay/node-steam-client/blob/1b0358a9b9baf498202e07285a6e137b7f87553f/steam-resources/protobufs/steamclient/steammessages_clientserver_login.proto)) :

The key is `two_factor_code` :

```
client.logOn({
	"account_name": "XXX",
	"password": "XXX",
	"two_factor_code": "XXX"
})
```

Hope this helps others too ! Thanks for the handy client wrapper !

**Comment by DoctorMcKay** [comment]
It's worth noting that you're *probably* looking for [steam-user](https://github.com/DoctorMcKay/node-steam-user). It's a much more complete library which uses this at a lower level.

**Comment by Coriou** [comment]
Yes @DoctorMcKay, in the end that's what I did instead of trying to build my own requests from steam-client, I noticed everything was already there and working well in steam-user :) 

Thanks so much, you saved me a lot of time !
