### ISSUE TITLE
Error: Unknown connection protocol

### ISSUE THREAD

**Issue by Vinipux322** [DoctorMcKay/node-steam-client#13]
I use proxy to connect on steam.
var Steam = require('steam-client')
var useProxy = new Steam.CMClient({
	localAddress: '94.350.224.32', 
	localPort: 2021
});
var client = new SteamUser(useProxy);
And get this error on connect:
![image](https://user-images.githubusercontent.com/36007766/35636758-45a28fac-06c3-11e8-9841-37605b621d2a.png)

**Comment by DoctorMcKay** [comment]
Please re-read the docs because you aren't doing that right.
