### ISSUE TITLE
Timeouts aren't implemented correctly

### ISSUE THREAD

**Issue by apapirovski** [DoctorMcKay/node-steam-client#16]
Hi there,

This recently came up on the Node.js tracker due to a bug report from upgrading to v10.0.0. The timeouts aren't quite implemented correctly as you can see below:

https://github.com/DoctorMcKay/node-steam-client/blob/894660239cb41dbc87ba090df1532277726033c2/lib/tcp_connection.js#L102-L111

As you'll note, the function from the socket is just assigned straight to the connection but that doesn't preserve the context (this) reference and the TCPConnection doesn't have an `_onTimeout` method which means that even if a timeout occurs, it won't fire or do anything.

While this behaviour now throws in v10.0.0 which makes the package not run on Node.js 10.x, it also wasn't ever working correctly prior to 10.x.

Cheers!

**Comment by DoctorMcKay** [comment]
Thanks, I appreciate you taking the time to open an issue here.
