### ISSUE TITLE
the "connected" event is never triggered

### ISSUE THREAD

**Issue by dmetree01** [DoctorMcKay/node-steam-client#23]
All standard steam servers addresses from "Steam.servers" variable are dead. unable to connect to steam with this library out of the box.

**Comment by DoctorMcKay** [comment]
This module is essentially deprecated, and I should probably tag it as such.

You should probably use [steam-user](https://github.com/DoctorMcKay/node-steam-user) instead for whatever you want to do.

**Comment by dmetree01** [comment]
Ok. Thanks for replying.
