### ISSUE TITLE
Doesn't work after latest steam update

### ISSUE THREAD

**Issue by aavvaavvaa** [DoctorMcKay/node-steam-client#25]
I mainly using cmclient with steam-user to set the ipv6 proxies, but after latest steam update it won't work, 
so i tried to test the normal steam-client to figure it out the problem but even a default snippet doesn't work it stucks on steamClient.connect()

```
var steamClient = new Steam.CMClient()
steamClient.connect();
steamClient.on('connected', function() {
	console.log('connected to SC')
    steamClient.logOn({
        "account_name": "",
        "password": ""
    });
});
steamClient.on('logOnResponse', function(details) {console.log('logOn response')});
```

**Comment by DoctorMcKay** [comment]
This is not supported anymore.
