### ISSUE TITLE
SOCKS proxy support for TCP connections

### ISSUE THREAD

**Issue by waylaidwanderer** [DoctorMcKay/node-steam-client#5]
I actually tried doing this myself but couldn't get it working properly.

https://github.com/DoctorMcKay/node-steam-client/blob/master/lib/tcp_connection.js

Would require changing the Socket class to another package that supports socks proxies.

**Comment by DoctorMcKay** [comment]
HTTP proxy support is available in v2.3.0-beta1 (currently `beta` tag on npm). SOCKS support is not planned at this time because I don't want to add any dependencies.
