### ISSUE TITLE
TypeError: "localAddress" option must be a valid IP: [object Object]

### ISSUE THREAD

**Issue by mworkg** [DoctorMcKay/node-steam-client#9]
I use proxy to connect on steam.
` let useProxy = new CMClient();`
 `       useProxy.bind({`
      `      localAddress: '5.189.204.190',`
     `       localPort: 1085`
 `       });`
   `     let client = new SteamUser(useProxy); `
And get this error on connect:
![0zejureqtkugkoih9ulwwa](https://user-images.githubusercontent.com/19779985/27514924-a0728f8e-59a0-11e7-8b1c-96f328d37062.png)

**Comment by DoctorMcKay** [comment]
Please re-read the documentation carefully. You shouldn't be passing an object to bind().
